name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_AGGREGATE: 1
      DOCKER_BUILDKIT: 1

    strategy:
      matrix:
        ubuntu_version:
          - 20.04
          - 22.04

    steps:
      - name: Checkout code

        uses: actions/checkout@v4
      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/srnjak-dev-playground:latest \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/srnjak-dev-playground:ubuntu-${{ matrix.ubuntu_version }} \
            -t ${{ vars.DOCKER_HUB_USERNAME }}/srnjak-dev-playground:ubuntu-${{ matrix.ubuntu_version }}-${{ github.run_number }} \
            --build-arg UBUNTU_VERSION=${{ matrix.ubuntu_version }} \
            --push .
